// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibzenqijdjpjcxrdhmvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliemVucWlqZGpwamN4cmRobXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMzU3ODMsImV4cCI6MjA1MTYxMTc4M30.Pp1If47k1Klk3xY9T2UX9VyXhquqEVFYcnd5KxVepvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);